name: Daily Surf Check

on:
  schedule:
    # Run at 8 AM Pacific Time (15:00 UTC)
    - cron: '0 15 * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  check-conditions:
    runs-on: ubuntu-latest
    steps:
      - name: Check surf conditions
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST "${{ secrets.NETLIFY_SITE_URL }}/api/check-forecast" \
            -H "Content-Type: application/json" \
            -d '{"checkType": "scheduled"}')
          
          http_code=$(echo "$response" | tail -n1)
          content=$(echo "$response" | sed '$d')
          
          echo "Response code: $http_code"
          echo "Response content: $content"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: Received HTTP status $http_code"
            exit 1
          fi 